/*
 * File: app/view/LoginPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.LoginPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.loginpanel',

    config: {
        layout: {
            align: 'center',
            pack: 'center',
            type: 'vbox'
        },
        items: [
            {
                xtype: 'container',
                cls: [
                    'logo'
                ],
                height: 221,
                ui: '',
                width: '100%'
            },
            {
                xtype: 'formpanel',
                maxWidth: 1024,
                width: 300,
                flex: 1,
                items: [
                    {
                        xtype: 'textfield',
                        margin: '0, 0, 5, 0',
                        label: 'Username',
                        name: 'username'
                    },
                    {
                        xtype: 'passwordfield',
                        margin: '0, 0, 10, 0',
                        label: 'Password',
                        labelWrap: true,
                        name: 'password'
                    },
                    {
                        xtype: 'container',
                        margin: '10 0 0 0',
                        padding: '',
                        right: 15,
                        items: [
                            {
                                xtype: 'button',
                                margin: '',
                                width: 86,
                                text: 'Submit'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container'
            }
        ]
    }

});