/*
 * File: app/view/Welcome.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Welcome', {
    extend: 'Ext.Panel',
    alias: 'widget.welcomepanel',

    config: {
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Go SignMeUp'
            },
            {
                xtype: 'container',
                height: 196,
                width: 318
            },
            {
                xtype: 'container',
                items: [
                    {
                        xtype: 'segmentedbutton',
                        layout: {
                            align: 'center',
                            pack: 'center',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                text: 'Current'
                            },
                            {
                                xtype: 'button',
                                minWidth: 100,
                                text: 'Past'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'searchfield',
                label: ''
            },
            {
                xtype: 'container'
            },
            {
                xtype: 'list',
                itemTpl: [
                    '<div>List Item {string}</div>'
                ]
            },
            {
                xtype: 'list',
                height: 159,
                itemTpl: [
                    '<div>List Item {string}</div>'
                ]
            }
        ]
    }

});